---
- name: Setup IRIS Staging Client
  hosts: stage
  vars:
    teardown: false

  pre_tasks:
    # apt housekeeping
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: dist
        update_cache: true
        cache_valid_time: 3600

    # upgrade pip
    - name: Upgrade pip module
      pip:
        name: pip
        state: latest

  tasks:
    - name: Execute stage role
      include_role:
        name: stage
