---
# IRIS snap build server
build:
  hosts:
    iris-build:
      ansible_host: 192.168.2.51
      ansible_user: ubuntu

# IRIS staging/integration server
stage:
  hosts:
    iris-stage:
      ansible_host: 192.168.2.41
      ansible_user: ubuntu
      hostname: iris-stage

# IRIS snap deployment server
deploy:
  hosts:
    iris-deploy:
      ansible_host: 192.168.2.53
      ansible_user: ubuntu

# full continous deployment pipeline
pipeline:
  children:
    build:
    stage:
    deploy:
