#!/bin/bash
OKG="\033[92m"
OKB="\033[94m"
NC="\033[0m"

printf "%b" "${OKB}Boot config setup${NC}\n"
# copy usercfg to /boot/firmware for screen orientation (portait mode on 1920x1080 monitors)
sudo cp firmware/* /boot/firmware/.
printf "%b" "${OKG} ✓ ${NC} complete\n"

# install node apt packages
printf "%b" "${OKB}Installing node dependancies${NC}\n"
sudo apt update -y
sudo apt upgrade -y
xargs -a node-dependancies.txt sudo apt install -y
printf "%b" "${OKG} ✓ ${NC} complete\n"

# hostname setup
printf "%b" "${OKB}Setting hostname${NC}\n"
read -rp "Setup a hostname: " hostname
sudo hostnamectl set-hostname "$hostname"
sudo avahi-set-host-name "$hostname"
printf "%b" "${OKG} ✓ ${NC} complete\n"

# disable wlan interfaces
sudo systemctl disable wpa_supplicant
# allow routed connections through firewall
sudo ufw default allow routed

# proceeding message
printf "%b" "${OKB}Your node ${OKG}$LOGNAME@$hostname${OKB} is ready! Try opening an ssh connection. ${NC}\n"