#!/bin/bash

set -e

usbboot(){
    cd usbboot || exit 1
    echo "Insert compute module into master SO-DIMM"
    sudo ./rpiboot -v
    cd ..
}

flash(){
    diskutil list
    read -rp 'Specify disk write location (ie /dev/disk2): ' disk
    printf "%b" "Unmounting${OKG} $disk ${NC}...\n"
    diskutil unmountDisk "$disk"
    printf "%b" "${OKG} ✓ ${NC} complete\n"
    cd build
    img="ubuntu-20.04-cm3.img"
    printf "%b" "${OKB}Flashing $img to $disk ...${NC}\n"
    pv "$img" | sudo dd bs=1m of="$disk"
    printf "%b" "${OKB}Ejecting $disk ...${NC}\n"
    diskutil eject "$disk"
    printf "%b" "${OKG} ✓ ${NC} complete\n"
    cd -
}

printf "%b" "${UNDERLINE}Please verify the following:${NC}\n"
echo " 1. The turingpi is ON"
echo " 2. The turingpi USB flash slave jumper is set"
echo " 3. This local machine is connected to the slave micro usb flash port"

read -rp "Press any key to continue ..."

printf "%b" "${OKB}Starting eMMC Flashing Service ${NC}\n"
usbboot && printf "%b" "${OKG} ✓ ${NC} complete\n" || 
	( printf "%b" "${FAIL} ✗ ${NC} usbboot sequence failed.\n" && exit 1 )

sleep 2

flash && printf "%b" "${OKG} ✓ ${NC} complete\n" || 
	( printf "%b" "${FAIL} ✗ ${NC} emmc flash failed.\n" && exit 1 )

printf "%b" "${OKG} ✓ ${NC} Completed eMMC Flashing Service"