#!/bin/bash

set -e

printf "%b" "${WARN} NOTE: Before executing be sure that the new user (incuvers-tp) is setup first! Follow the instructions in docs/username.md to setup incuvers-tp user.${NC}\n"

# assume node name is set to incuvers-tp
node_name="incuvers-tp"
read -rp 'Node IP address (ie 192.168.2.67): ' node_address

printf "%b" "${OKB}Configuring ssh key authorization with your machine to ${OKG}$node_name${OKB}@${OKG}$node_address${NC}\n"
pub_ssh=$(< ~/.ssh/id_rsa.pub)
echo "$pub_ssh" | ssh -T "$node_name"@"$node_address" "mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys && chmod -R go= ~/.ssh && cat >> ~/.ssh/authorized_keys"

printf "%b" "${OKB}Executing node build job @ ${OKG}$node_address${OKB}...${NC}\n"
rsync -a node "$node_name"@"$node_address":~/.
ssh -t "$node_name"@"$node_address" "cd node && sudo apt update -y && ./scripts/node-build"