#!/bin/bash

set -e

IMG="https://cdimage.ubuntu.com/releases/20.04.1/release/ubuntu-20.04.1-preinstalled-server-arm64+raspi.img.xz?_ga=2.62032367.234707340.1608229182-200893871.1586502931"
NAME="ubuntu-20.04-cm3.img.xz"

build(){
  cd build && unxz --keep "$NAME" && cd -
}

build_usbboot(){
  git submodule update --init --recursive
  echo "Syncing with upstream usbboot"
  git submodule update --remote
  cd usbboot && make && cd -
}

printf "%b" "${OKB}Installing homebrew dependancies ...${NC}\n"
# xargs brew install < dependencies.txt
printf "%b" "${OKG} ✓ ${NC} complete\n"

printf "%b" "${OKB}Preparing usbboot submodule ...${NC}\n"

if build_usbboot ; then
    printf "%b" "${OKG} ✓ ${NC} complete\n"
else
    printf "%b" "${FAIL} ✗ ${NC} usbboot build failed.\n"
    exit 1
fi

mkdir build
printf "%b" "${OKB}Fetching latest Ubuntu 20.04 release for CM3+${NC}\n"
curl -L "$IMG" --output build/"$NAME"
printf "%b" "${OKG} ✓ ${NC} complete\n"

echo "Extracting Ubuntu img ..."
if build ; then
    printf "%b" "${OKG} ✓ ${NC} complete\n"
else
    printf "%b" "${FAIL} ✗ ${NC} Failed to extract ubuntu image.\n"
    exit 1
fi