---
# install iris staging client from python packaging index
- name: Install python3 and pip3
  become: true
  apt:
    name:
      - python3
      - python3-pip

- name: Copy firmware config files
  become: true
  copy:
    src: "monitor/{{ item }}"
    dest: "/boot/firmware/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - cmdline.txt
    - config.txt
    - syscfg.txt
    - uboot.env
    - usercfg.txt
