---
# name architecture
- debug:
    msg: "Installing docker on {{ host_arch }}"

# install docker on target architecture (id'd by main.yaml)
- name: Update apt cache and install apt packages
  become: true
  apt:
    name:
      - python3-pip
      - libffi-dev
      - libssl-dev
      - apt-transport-https
      - ca-certificates
      - software-properties-common
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  become: true
  apt_repository:
    repo: "deb [arch={{ host_arch }}] https://download.docker.com/linux/ubuntu focal stable"
    state: present

# ignore post install error for docker
- name: Install docker-ce
  become: true
  apt:
    name:
      - docker-ce
    state: latest
  ignore_errors: true

- name: Create docker group
  group:
    name: docker
    state: present

- name: Apply usermod to append docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: reboot
  become: true
  reboot:
