---
- name: Teardown Github Actions Continuous Deployment Server
  hosts: cd
  become: true

  vars_files:
    - cd-vars.yaml

  handlers:
    - name: verify gar service
      service:
        name: "actions.runner.{{ organization }}.{{ hostname }}.service"
        state: stopped

  tasks:
    - name: Stop github actions runner service
      command: >
        chdir="{{ actions_runner }}" ./svc.sh stop
      ignore_errors: true
      notify: verify gar service

    # this cannot be run with sudo
    - name: Uninstall github actions runner
      command: >
        chdir="{{ actions_runner }}" ./svc.sh uninstall
      ignore_errors: true

    - name: Generate runner token in admin:org scope
      become: false
      uri:
        url: "{{ github_base_path }}/orgs/{{ organization }}/actions/runners/remove-token"
        method: POST
        headers:
          Authorization: "token {{ pa_token }}"
          Accept: application/vnd.github.v3+json
        status_code: 201
      register: runner_token

    - name: Remove configuration
      become: false
      command: >
        {{ actions_runner }}/config.sh remove --url {{ organization_url }} --token {{ runner_token.json.token }}
      ignore_errors: true

    - name: Upstream monitor deploy key removal 
      script: scripts/remove_key.sh {{ pa_token }} Incuvers monitor monitor_deploy_key

    - name: Upstream icb deploy key removal
      script: scripts/remove_key.sh {{ pa_token }} Incuvers icb icb_deploy_key

    - name: Remove ssh config
      file:
        path: /home/ubuntu/.ssh/config
        state: absent

  post_tasks:
    - name: Clean Github Actions artefact path
      file:
        state: absent
        path: "{{ actions_runner }}/"

    - name: Uninstall packages
      pip:
        state: absent
        name:
          - pexpect
          - boto3
