---
- name: Teardown Github Actions Continuous Deployment Server
  hosts: cd
  become: true

  vars_files:
    - cd-vars.yaml

  handlers:
    - name: verify gar service
      service:
        name: "actions.runner.{{ organization }}.{{ hostname }}.service"
        state: stopped

  tasks:
    - name: Stop github actions runner service
      command: >
        chdir="{{ actions_runner }}" ./svc.sh stop
      ignore_errors: true
      notify: verify gar service

    # this cannot be run with sudo
    - name: Uninstall github actions runner
      command: >
        chdir="{{ actions_runner }}" ./svc.sh uninstall
      ignore_errors: true

    - name: Generate runner token in admin:org scope
      become: false
      uri:
        url: "{{ github_base_path }}/orgs/{{ organization }}/actions/runners/remove-token"
        method: POST
        headers:
          Authorization: "token {{ pa_token }}"
          Accept: application/vnd.github.v3+json
        status_code: 201
      register: runner_token

    - name: Remove configuration
      become: false
      command: >
        {{ actions_runner }}/config.sh remove --url {{ organization_url }} --token {{ runner_token.json.token }}

    - name: Read icb deploy key
      slurp:
        src: ~/.ssh/icb_deploy_key.pub
      register: icb_deploy_key

    - name: Read monitor deploy key
      slurp:
        src: ~/.ssh/monitor_deploy_key.pub
      register: monitor_deploy_key

    - name: Remove ssh config
      file:
        path: ~/.ssh/config
        state: absent

    - name: Remove deploy keys from Incuvers:monitor and Incuvers:icb repositories
      become: false
      uri:
        url: "{{ item.url }}"
        method: POST
        headers:
          Authorization: "token {{ pa_token }}"
          Accept: application/vnd.github.v3+json
        body: "{{ item.body }}"
        body_format: json
        status_code: 201
      with_items:
        - url: "{{ github_base_path }}/repos/{{ organization }}/monitor/keys/{{ icb_key_id }}"
          body:
            title: "snap build server"
            key: "{{ monitor_deploy_key }}"
            read_only: true
        - url: "{{ github_base_path }}/repos/{{ organization }}/icb/keys/{{ icb_key_id }}"
          body:
            title: "snap build server"
            key: "{{ icb_deploy_key }}"
            read_only: true

  post_tasks:
    - name: Clean Github Actions artefact path
      file:
        state: absent
        path: "{{ actions_runner }}/"
