---
actions_runner: /opt/actions-runner
runner_name: snap-build
gar_work_folder: work
repository_name: monitor
repository_owner: Incuvers
repository: "https://github.com/{{ repository_owner }}/{{ repository_name }}"
token: AGNYXHBG74T2YZIESOCO4TTADSONW
gar_version: 2.276.1
gar_checksum: sha256:77ba7bfe67f266df70cd040fbea6d433d1a063596056160cd5e3c439ac47fd70
arch: arm64
github_servers:
  - github.com
  - api.github.com
  - codeload.github.com
  # - *.actions.githubusercontent.com
