---
- name: Setup IRIS Build Server
  hosts: build

  vars_files:
    - ib-vars.yaml

  handlers:
    - name: verify actions runner service
      service:
        name: "actions.runner.{{ organization }}.{{ hostname }}.service"
        state: started

  pre_tasks:
    - name: Update apt cache and install apt packages
      become: true
      apt:
        name:
          - avahi-utils
          - python3-pip
        state: present
        update_cache: true

    - name: Install pip packages for ansible modules
      become: true
      pip:
        name:
          - pexpect
          - boto3

    # snapcraft install is a seperate task due to its strict channel and confinement parameters
    - name: Install snapcraft
      become: true
      snap:
        name:
          - snapcraft
        classic: true
        channel: candidate

    - name: Set hostname
      become: true
      hostname:
        name: "{{ hostname }}"

    - name: Configure avahi with local hostname
      command: >
        avahi-set-host-name {{ hostname }}
      ignore_errors: true

    - name: Verify avahi is running
      service:
        name: avahi-daemon
        state: started

    # use wait_for to validate github servers can be reached from the target node
    - name: Validate connection to github.com servers
      wait_for:
        host: "{{ item }}"
        port: 80
        timeout: 30
        active_connection_states: ESTABLISHED
      with_items: "{{ github_servers }}"

    # create install directory in /opt
    - name: Setup github actions directory
      become: true
      file:
        path: "{{ actions_runner }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0777

  tasks:
    - name: Remove pre-existing RSA deploy keys
      file:
        path:
          - /home/ubuntu/.ssh/{{ item }}_deploy_key.pub
          - /home/ubuntu/.ssh/{{ item }}_deploy_key
        state: absent
      with_items:
        - monitor
        - icb

    - name: Generate RSA deploy keys
      command: ssh-keygen -b 4096 -t rsa -f /home/ubuntu/.ssh/"{{ item }}"_deploy_key -q -N ""
      args:
        creates:
          - /home/ubuntu/.ssh/{{ item }}_deploy_key.pub
          - /home/ubuntu/.ssh/{{ item }}_deploy_key
      with_items:
        - monitor
        - icb

    - name: Configure lxd
      become: true
      shell: |
        lxd init --auto
        usermod -a -G lxd {{ ansible_user }}

    - name: Download github actions runner
      get_url:
        url: "https://github.com/actions/runner/releases/download/v{{ gar_version }}/actions-runner-linux-{{ arch }}-{{ gar_version }}.tar.gz"
        dest: "{{ download_dir }}/gar-{{ gar_version }}.tgz"
        checksum: "{{ gar_checksum }}"

    - name: Extract github actions runner
      unarchive:
        src: "{{ download_dir }}/gar-{{ gar_version }}.tgz"
        dest: "{{ actions_runner }}"
        remote_src: true
        mode: 0777
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        creates: "{{ actions_runner }}/README.md"

    - name: Read and encode deploy keys
      slurp:
        src: "{{ item }}"
      register: deploy_keys
      loop:
        - /home/ubuntu/.ssh/monitor_deploy_key.pub
        - /home/ubuntu/.ssh/icb_deploy_key.pub

    - name: Copy ssh config for key alias
      copy:
        src: config
        dest: /home/ubuntu/.ssh/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644

    - name: Add deploy keys to Incuvers:monitor and Incuvers:icb repositories
      uri:
        url: "{{ item.url }}"
        method: POST
        headers:
          Authorization: "token {{ pa_token }}"
          Accept: application/vnd.github.v3+json
        body: "{{ item.body }}"
        body_format: json
        status_code: 201
      with_items:
        - url: "{{ github_base_path }}/repos/{{ organization }}/monitor/keys"
          body:
            title: "snap build server"
            key: "{{ deploy_keys['results'][0]['content'] | b64decode }}"
            read_only: true
        - url: "{{ github_base_path }}/repos/{{ organization }}/icb/keys"
          body:
            title: "snap build server"
            key: "{{ deploy_keys['results'][1]['content'] | b64decode }}"
            read_only: true

    - name: Generate Github Actions Runner token
      uri:
        url: "{{ github_base_path }}/orgs/{{ organization }}/actions/runners/registration-token"
        method: POST
        headers:
          Authorization: "token {{ pa_token }}"
          Accept: application/vnd.github.v3+json
        status_code: 201
      register: runner_token

    - name: Configure actions runner
      expect:
        command: >
          {{ actions_runner }}/config.sh --url {{ organization_url }} --token {{ runner_token.json.token }}
        responses:
          (.*)Enter the name of runner:(.*): ""
          (.*)Enter any additional labels \(ex. label-1,label-2\):(.*): ""
          (.*)Enter name of work folder:(.*): "{{ gar_work_folder }}"
          (.*)Would you like to replace the existing runner? (Y/N)(.*): ""
      ignore_errors: true

    - name: Install github actions runner
      become: true
      command: >
        chdir="{{ actions_runner }}" ./svc.sh install

    - name: Start github actions runner service
      become: true
      command: >
        chdir="{{ actions_runner }}" ./svc.sh start
      notify: verify actions runner service

  post_tasks:
    - name: Clean build artefacts
      file:
        state: absent
        path: "{{ download_dir }}/gar-{{ gar_version }}.tgz"

    - name: Reboot to apply group mods
      become: true
      reboot:
