---
- name: Teardown IRIS Deployment Server
  hosts: deploy

  vars_files:
    - id-vars.yaml

  pre_tasks:
    # use wait_for to validate github servers can be reached from the target node
    - name: Validate connection to github.com servers
      wait_for:
        host: "{{ item }}"
        port: 80
        timeout: 30
        active_connection_states: ESTABLISHED
      with_items: "{{ github_servers }}"

  tasks:
    - name: Stop github actions runner service
      command: >
        chdir="{{ actions_runner }}" ./svc.sh stop
      ignore_errors: true

    # this cannot be run with sudo
    - name: Uninstall github actions runner
      command: >
        chdir="{{ actions_runner }}" ./svc.sh uninstall
      ignore_errors: true

    - name: Retrieve Github Actions Runner token
      uri:
        url: "{{ github_base_path }}/orgs/{{ organization }}/actions/runners/remove-token"
        method: POST
        headers:
          Authorization: "token {{ pa_token }}"
          Accept: application/vnd.github.v3+json
        status_code: 201
      register: runner_token

    - name: Remove configuration
      command: >
        {{ actions_runner }}/config.sh remove --url {{ organization_url }} --token {{ runner_token.json.token }}
      ignore_errors: true

  post_tasks:
    - name: Clean Github Actions artefact path
      become: false
      file:
        state: absent
        path: "{{ actions_runner }}/"

    - name: Uninstall pip packages
      become: false
      pip:
        state: absent
        name:
          - pexpect

    - name: Uninstall apt packages
      become: false
      apt:
        state: absent
        name:
          - avahi-utils
          - python3-pip

    - name: Reset hostname
      hostname:
        name: ubuntu

    - name: Reboot to apply hostname changes
      become: true
      reboot:
