---
hostname: iris-deploy
actions_runner: /opt/actions-runner
gar_work_folder: work
organization: Incuvers
organization_url: "https://github.com/{{ organization }}"
gar_version: 2.276.1
gar_checksum: sha256:77ba7bfe67f266df70cd040fbea6d433d1a063596056160cd5e3c439ac47fd70
arch: arm64
github_base_path: "https://api.github.com"
github_servers:
  - github.com
  - api.github.com
  - codeload.github.com
