---
# DOCKER IMAGE BUILD SERVER
# -------------------------
# Builds monitor environment and pushes to docker hub

- name: Setup Docker Image Builder
  hosts: docker
  pre_tasks:
    # apt housekeeping
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 3600

  roles:
    - actions
    - docker

  post_tasks:
    # cleanup
    - name: Clean github actions install artefacts
      file:
        state: absent
        path: "{{ download_dir }}/gar-{{ gar_version }}.tgz"
