---
- name: Setup Tests CI Server
  hosts: ci
  pre_tasks:
    # apt housekeeping
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 3600
        lock_timeout: 300

  roles:
    - actions
    - docker
