---
- name: Setup IRIS Staging Server
  hosts: stage

  vars_files:
    - is-vars.yaml

  tasks:
    - name: Install staging client
      pip:
        name: iris-stage
        extra_args: --upgrade

    - name: Copy aws and machine secrets
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0664
      with_items:
        - src: .secrets
          dest: /home/ubuntu/.secrets
        - src: .aws
          dest: /home/ubuntu/.aws

    - name: Copy service file for start-on-boot
      become: true
      copy:
        src: iris-stage.service
        dest: /etc/systemd/system/iris-stage.service
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644

    - name: Enable service
      become: true
      service:
        name: iris-stage
        enabled: true

    - name: Reboot to validate service startup
      become: true
      reboot:

    - name: Verify service is active
      service:
        name: iris-stage
        state: started
