---
# set the system hostname for job identification
- name: Set system hostname
  become: true
  hostname:
    name: "{{ hostname }}"

# install iris staging client from python packaging index
- name: Install staging client
  become: true
  pip:
    name: iris-stage
    state: latest

# copy aws and iris runtime certification and configuration files to $HOME
- name: Copy aws and machine secrets
  copy:
    src: "{{ item }}"
    dest: /home/ubuntu/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0664
  with_items:
    - .secrets
    - .aws

# configure service start on boot by copying systemd file
- name: Copy service file for start-on-boot
  become: true
  copy:
    src: iris-stage.service
    dest: /etc/systemd/system/iris-stage.service
    owner: root
    group: root
    mode: 0644

# enable service; reboot and verify it is active
- name: Enable service
  become: true
  service:
    name: iris-stage
    enabled: true

- name: Reboot
  become: true
  reboot:

- name: Verify service
  service:
    name: iris-stage
    state: started
