---
name: ansible
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  playbook-lint:
    name: Ansible Playbook Linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Install test dependencies.
        run: sudo apt install ansible -y

      - name: Inject dummy vault key for ansible-playbook syntax checking
        run: |
          echo "ci-password" > ./secrets/vault.key"

      - name: Run ansible-playbook linter.
        run: |
          ansible-playbook playbooks/*.yaml --syntax-check 
